version: '3.7'
services:
  php:
    build: .
    links:
      - mongo
    volumes:
      - .:/application

  nginx:
    image: nginx:latest
    ports:
      - 8080:80
    links:
      - php
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - .:/application

  mongo:
      image: mongo:4
      restart: always
      volumes:
          - db-volume:/data/db
      environment:
          MONGO_INITDB_ROOT_USERNAME: mongoadmin
          MONGO_INITDB_ROOT_PASSWORD: secret

  mongo-express:
    image: mongo-express
    restart: always
    links:
        - mongo
    ports:
        - 8081:8081
    environment:
        ME_CONFIG_MONGODB_ADMINUSERNAME: mongoadmin
        ME_CONFIG_MONGODB_ADMINPASSWORD: secret

  rabbit:
      container_name: rabbit_server.rabbit
      image: "rabbitmq:3-management"
      hostname: "rabbit"
      environment:
          - RABBITMQ_ERLANG_COOKIE
          - RABBITMQ_DEFAULT_USER
          - RABBITMQ_DEFAULT_PASS
          - RABBITMQ_DEFAULT_VHOST
      ports:
          - ${RABBITMQ_CLIENT_PORT}:15672
          - ${RABBITMQ_SERVER_PORT}:5672
      labels:
          NAME: "rabbitmq"
      volumes:
          - ./docker/rabbit-server/rabbit/enabled_plugins:/etc/rabbitmq/enabled_plugins

volumes:
  db-volume:
